### ISSUE TITLE
Cannot resolve com.github.WangJi92:mybatis-sql-log:1.0.4

### ISSUE THREAD

**Issue by liangle902** [WangJi92/mybatis-sql-log#10]
1.0.4.pom不能导入，1.0.3的可以

**Comment by WangJi92** [comment]
> 1.0.4.pom不能导入，1.0.3的可以

没有懂 什么意思

**Comment by liangle902** [comment]
<dependency>
            <groupId>com.github.WangJi92</groupId>
            <artifactId>mybatis-sql-log</artifactId>
            <version>1.0.4</version>
</dependency>

我提问的时候在maven中引入上述dependency，不管maven仓库设置为阿里云还是用maven默认源都不能引入
改成1.0.3的就可以了

刚才又试了一下，1.0.4的可以了，感谢感谢
