### ISSUE TITLE
mybatis-plus兼容问题

### ISSUE THREAD

**Issue by dimples9527** [WangJi92/mybatis-sql-log#11]
位于73行的这句代码
final DefaultParameterHandler parameterHandler = (DefaultParameterHandler) statementHandler.getParameterHandler();
如果使用的是mybatis-plus会报一个类型转换的错误：
MybatisParameterHandler不能转换为DefaultParameterHandler 
建议做一个判断

**Comment by WangJi92** [comment]
> 位于73行的这句代码
> final DefaultParameterHandler parameterHandler = (DefaultParameterHandler) statementHandler.getParameterHandler();
> 如果使用的是mybatis-plus会报一个类型转换的错误：
> MybatisParameterHandler不能转换为DefaultParameterHandler
> 建议做一个判断

提交一个pr 吧

**Comment by WangJi92** [comment]
1、去掉 //@AutoConfigureAfter(MybatisAutoConfiguration.class)
2、拦截器增加构造函数 从 配置里面获取
```java
@PostConstruct
        public void addPrintInterceptor() {
            for (SqlSessionFactory sqlSessionFactory : sqlSessionFactoryList) {
                final org.apache.ibatis.session.Configuration configuration = sqlSessionFactory.getConfiguration();
                MybatisSqlCompletePrintInterceptor printInterceptor = new MybatisSqlCompletePrintInterceptor(configuration);
                sqlSessionFactory.getConfiguration().addInterceptor(printInterceptor);
            }
        } 
```

3、不打印 属性 
ew.paramNameValuePairs 是 mybatis plus 里面的属性
```java
   // mybatis generator 中的参数不打印出来
                    if (!(propertyName.contains("frch_criterion")|| propertyName.contains("ew.paramNameValuePairs"))) {
                        paramValueStr = "/*" + propertyName + "*/" + paramValueStr;
                    } 
```
