### ISSUE TITLE
和pagehelper结合后打印sql不对，能麻烦看看么？

### ISSUE THREAD

**Issue by zqdl6** [WangJi92/mybatis-sql-log#2]
![image](https://user-images.githubusercontent.com/18321347/65103031-7be4f080-d9ff-11e9-8b15-da025b2eefee.png)

**Comment by WangJi92** [comment]
pagehelp地址：https://github.com/pagehelper/Mybatis-PageHelper
pagehelp spring boot支持：https://github.com/pagehelper/pagehelper-spring-boot

测试的Demo：[mybaits sql log Demo 工程](https://github.com/WangJi92/mybatis-log-demo/blob/master/README.md)
访问地址：http://127.0.0.1:7012/user/findAll

MyBatis Log 打印效果 
![image](https://user-images.githubusercontent.com/20874972/65350260-e53f4c00-dc17-11e9-9db1-7646676dceda.png)


原因：Interceptor 有先后顺序，打印sql应该是在最后一个执行。PageHelp中主要是因为PageHelp处理的时候，直接调用Executor的方法进行处理，没有调用invocation.proceed() 下一个拦截器处理。因此这里修改为使用 拦截StatementHandler 肯定不会错误【StatementHandler，语句处理器负责和JDBC层具体交互，包括prepare语句，执行语句，以及调用ParameterHandler.parameterize()设置参数。

**Comment by WangJi92** [comment]
总结了一下pagehelp的整个过程的使用 https://blog.csdn.net/u012881904/article/details/101127682
