### ISSUE TITLE
replaceFirst有个小瑕疵

### ISSUE THREAD

**Issue by bigblue311** [WangJi92/mybatis-sql-log#4]
https://github.com/WangJi92/mybatis-sql-log/blob/2d17c3eb0709cec287fac62f64eca6351d6ac497/src/main/java/com/mybatis/spring/boot/autoconfigure/MybatisSqlCompletePrintInterceptor.java#L135

当paramValueStr中包含$时会出现
java.lang.IllegalArgumentException: Illegal group reference

**Comment by WangJi92** [comment]
时间长了忘记修改了 
  sql = sql.replaceFirst("\\?", Matcher.quoteReplacement(paramValueStr));
1.0.3 版本修复
