### ISSUE TITLE
是否有配置参数可以管理该插件在不同环境下日志的输出

### ISSUE THREAD

**Issue by ghost** [WangJi92/mybatis-sql-log#6]
例如在springboot内随着启动的配置在dev和test环境下输出，切换到prod的时候就不再输出了

**Comment by WangJi92** [comment]
> 例如在springboot内随着启动的配置在dev和test环境下输出，切换到prod的时候就不再输出了

mybatis.print=true 通过spring 环境的配置 不配置就行了
